services:
  nginx:
    image: nginx-portainer:latest
    build: .
    ports:
      - "80:80"
    networks:
      - shared
    restart: unless-stopped

networks:
  shared:
    external: true
    name: shared