services:
  nginx:
    image: nginx-portainer:latest
    build: .
    ports:
      - "80:80"
    networks:
      - local-network
    restart: unless-stopped

networks:
  local-network:
    external: true
    name: local-network
